# Generated by Django 5.0.6 on 2024-07-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('nb_goals_user1', models.IntegerField()),
                ('nb_goals_user2', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(default='default.jpg', upload_to='upload')),
                ('status', models.CharField(default='Offline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentsGames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('Last 16', 'Last16'), ('Quarter-final', 'Quarterfinal'), ('Semi-final', 'Semifinal'), ('Final', 'Final')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.games')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.tournaments')),
            ],
        ),
        migrations.AddField(
            model_name='tournaments',
            name='host_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_host', to='pong.users'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_winner', to='pong.users'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Friend Request', 'Friend Request'), ('Accepted Friend Request', 'Accepted Friend Request')])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default='Pending')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.users')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='user1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_user1', to='pong.users'),
        ),
        migrations.AddField(
            model_name='games',
            name='user2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_user2', to='pong.users'),
        ),
        migrations.AddField(
            model_name='games',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner', to='pong.users'),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_games_played', models.IntegerField()),
                ('nb_games_won', models.IntegerField()),
                ('nb_goals_scored', models.IntegerField()),
                ('nb_goals_suffered', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.users')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_with', to='pong.users')),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_of', to='pong.users')),
            ],
            options={
                'unique_together': {('user1_id', 'user2_id')},
            },
        ),
    ]
