# Generated by Django 5.1 on 2024-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
