# Generated by Django 5.1.1 on 2024-10-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
