# Generated by Django 5.1.1 on 2024-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='tournament',
            field=models.BooleanField(default=False),
        ),
    ]
