# Generated by Django 5.0.7 on 2024-07-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournaments',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userstats',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(default='Pending'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='status',
            field=models.CharField(default='Open'),
        ),
        migrations.AlterField(
            model_name='tournamentsgames',
            name='phase',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
