# Generated by Django 5.1.1 on 2024-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='rally_lenght',
            new_name='rally_length',
        ),
        migrations.RenameField(
            model_name='userstats',
            old_name='max_rally_lenght',
            new_name='max_rally_length',
        ),
        migrations.AlterField(
            model_name='goals',
            name='ball_speed',
            field=models.FloatField(default=0),
        ),
    ]
