# Generated by Django 5.1.3 on 2024-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesstats',
            name='average_ball_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesstats',
            name='max_ball_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesstats',
            name='min_ball_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='max_ball_speed',
            field=models.FloatField(default=0),
        ),
    ]
