# Generated by Django 5.1 on 2024-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_tournamentsusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='nb_goals_user1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='nb_goals_user2',
            field=models.IntegerField(default=0),
        ),
    ]
