# Generated by Django 5.0.7 on 2024-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_rename_update_at_tournaments_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='Offline', max_length=7),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
