# Generated by Django 5.1.1 on 2024-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_userstats_nb_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='nb_tournaments_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='nb_tournaments_won',
            field=models.IntegerField(default=0),
        ),
    ]
