# Generated by Django 5.1.1 on 2024-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_rename_rally_lenght_goals_rally_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='quickest_game',
            field=models.IntegerField(default=2147483647),
        ),
    ]
