# Generated by Django 5.1 on 2024-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_games_duration_alter_games_nb_goals_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsusers',
            name='alias',
            field=models.CharField(max_length=64),
        ),
    ]
