# Generated by Django 5.1.1 on 2024-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_users_user_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='type',
            field=models.CharField(default='Local'),
        ),
    ]
