# Generated by Django 5.1.1 on 2024-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_games_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
