# Generated by Django 5.1.1 on 2024-09-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_games_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='tournament',
        ),
    ]
