# Generated by Django 5.1.1 on 2024-09-21 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_tournaments_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='ai_time_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='local_time_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='longest_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='max_ball_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='max_rally_lenght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='num_first_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='quickest_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='remote_time_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='tournament_time_played',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GamesStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longer_rally', models.IntegerField(default=0)),
                ('shorter_rally', models.IntegerField(default=0)),
                ('average_rally', models.IntegerField(default=0)),
                ('max_ball_speed', models.IntegerField(default=0)),
                ('min_ball_speed', models.IntegerField(default=0)),
                ('average_ball_speed', models.IntegerField(default=0)),
                ('greatest_deficit_overcome', models.IntegerField(default=0)),
                ('most_consecutive_goals', models.IntegerField(default=0)),
                ('biggest_lead', models.IntegerField(default=0)),
                ('bg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_games', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.games')),
                ('gdo_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdo_games', to=settings.AUTH_USER_MODEL)),
                ('mcg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcg_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(default=0)),
                ('rally_lenght', models.IntegerField(default=0)),
                ('ball_speed', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.games')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
